<?php

/**
 * Sekulich_MaropostOrder
 *
 * @author Natalia Sekulich <sekulich.n@gmail.com>
 */

/** @var $block \Sekulich\MaropostOrder\Block\Order\View */
/** @var \Sekulich\MaropostOrder\ViewModel\PriceFormatter $priceFormatter */
$priceFormatter = $block->getData('price_formatter');
$incrementId = $block->getRequest()->getParam('order_id');
?>

<div id="maropost-order-view" data-bind="scope:'maropostOrderView'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#maropost-order-view": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "maropostOrderView": {
                        "component": "Sekulich_MaropostOrder/js/maropost-order-view",
                        "orderId": "<?= $incrementId ?>",
                        "priceFormat": <?= /* @noEscape */ $priceFormatter->getPriceFormatJson() ?>,
                        "stripeConfig": <?=  /* @noEscape */ $block->getStripeConfig() ?>
                    }
                }
            }
        }
    }
</script>

<?= $this->getChildHtml('stripe-form'); ?>
